name: Create Release

on:
  push:
    branches: 
      - master
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        id: tag
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createRelease({
              owner: "DooomiT",
              repo: "spotify-api-project",
              tag_name: "${{ steps.tag.outputs.tagname }}",
              draft: true,
              generate_release_notes: true,
            });
        env: 
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
